version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - node_modules:/workspace/node_modules
      - web_node_modules:/workspace/web/node_modules
      - vscode-extensions:/home/vscode/.vscode-server/extensions
      - vscode-extensions-insiders:/home/vscode/.vscode-server-insiders/extensions
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use the same network as the application services
    network_mode: service:frontend
    
    environment:
      # Development environment variables
      NODE_ENV: development
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      # Docker socket
      DOCKER_HOST: unix:///var/run/docker-host.sock
      # Firebase configuration (for development)
      FIREBASE_PROJECT_ID: ai-startup-analyst-ba7f9
      GOOGLE_APPLICATION_CREDENTIALS: /workspace/serviceAccountKey.json
      
    # Add labels for better container management
    labels:
      - "devcontainer.local_folder=${WORKSPACE_FOLDER:-/workspace}"

volumes:
  node_modules:
  web_node_modules:
  vscode-extensions:
  vscode-extensions-insiders: